### ISSUE TITLE
EntityMetadataWrapperException

### ISSUE THREAD

**Issue by lsolesen** [discimport/discimport-build#45]
Cannot access e.g. http://discimport.dk/discgolf/nuke-z-first-run

Getting:

```
EntityMetadataWrapperException: Unable to get the data property value as the parent data structure is not set. i EntityStructureWrapper->getPropertyValue() (linje 438 af /data/disk/o1/static/ck-20151128/profiles/commerce_kickstart/modules/contrib/entity/includes/entity.wrapper.inc).
```

**Comment by lsolesen** [comment]
These also creates problems.

http://discimport.dk/discgolf/eagle-kc-pro-12x-0
http://discimport.dk/discgolf/eagle-kc-pro-11x

**Comment by mglaman** [comment]
I think it might be this issue, https://www.drupal.org/node/1872922#comment-10742028. Made patch for CK2 to use it, testing.

**Comment by mglaman** [comment]
I committed the patch, can you give it a test?

**Comment by lsolesen** [comment]
commerce_kickstart-7.x-2.31 downloaded.

can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?

## The text leading up to this was:

|diff --git a/drupal-org.make b/drupal-org.make
|index 283304d..29c5044 100644
|--- a/drupal-org.make

## |+++ b/drupal-org.make

File to patch:
Skip this patch? [y]
Skipping patch.
1 out of 1 hunk ignored

Unable to patch commerce_kickstart with discount_patch-2649950-2.patch.

**Comment by mglaman** [comment]
Ah because it applies against -dev, not the release.

**Comment by lsolesen** [comment]
https://travis-ci.org/discimport/discimport-build#L493
@mglaman seems to be problems still.

**Comment by mglaman** [comment]
Ah, that's because in -dev they got merged into the main module. I'll
update.

**Comment by lsolesen** [comment]
@mglaman did you ever get around to fixing this?

**Comment by mglaman** [comment]
@lsolesen fix incoming

**Comment by lsolesen** [comment]
@mglaman Unable to download /ck2-use-discounts-dev.patch. --> seems like the link is missing?

**Comment by mglaman** [comment]
:/ Where is it saying that? The Travis-CI found it. It's using the local path.

**Comment by lsolesen** [comment]
Hm. It is on boa it is saying that :)
Den 19/01/2016 02.17 skrev "Matt Glaman" notifications@github.com:
